# Generated by Django 5.0.4 on 2024-04-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitura', to='Sensores.sensor'),
        ),
    ]
